### ISSUE TITLE
Adding some related projects

### ISSUE THREAD

**Issue by ashumeow** [iamOgunyinka/Hend#1]
Just sharing... ;)

[1] https://github.com/rg3/youtube-dl
[2] https://github.com/kataras/Librekit

**Comment by iamOgunyinka** [comment]
Sharing what? I don't understand, you could fork this instead of sharing

**Comment by ashumeow** [comment]
I found that you were trying to build a youtube search and download utility. So, i shared some repos to keep you motivated in starting your project. And now, you are forking me up instead of thanking me. :|

**Comment by iamOgunyinka** [comment]
I said I didn't understand what you were saying, is that offensive? If it is, I'm sorry. I already finished the project. I'll push it to the Hend repo in few hours
Josh

**Comment by ashumeow** [comment]
Not taking it offensive at all Mr.Forker... Alright Josh... Keep pushing it forward!

**Comment by iamOgunyinka** [comment]
okay

**Comment by ashumeow** [comment]
kkkkkkkkkkkkkkkkkkkkkkkk

**Comment by iamOgunyinka** [comment]
The code is up.
Josh

**Comment by ashumeow** [comment]
Already saw it... And i clicked "watch" like more than 12 hours ago (^_^)
